# Generated by Django 4.0.2 on 2022-02-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_profile_img_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sill',
            new_name='Skill',
        ),
    ]
